server:
    port: 8090

spring:
    datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/formula?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=false
      username: inzent
      password: inzent!1.

    jwt:
      header: Authorization
      secret: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK

    redis:
      host: localhost
      port: 6379
#mybatis:
#  mapper-locations: classpath:mapper/**.xml

